export const SEARCH = 'CHARACTER/SEARCH';
export const FETCH_ALL_START = 'CHARACTER/FETCH_ALL_START';
export const FETCH_ALL_SUCCESS = 'CHARACTER/FETCH_ALL_SUCCESS';
export const FETCH_ALL_ERROR = 'CHARACTER/FETCH_ALL_ERROR';
export const FETCH_DETAIL_START = 'CHARACTER/FETCH_DETAIL_START';
export const FETCH_DETAIL_SUCCESS = 'CHARACTER/FETCH_DETAIL_SUCCESS';
export const FETCH_DETAIL_ERROR = 'CHARACTER/FETCH_DETAIL_ERROR'; 